package domain

import (
	"strings"
	"testing"
)

func TestPOBrowserTemplateCoversPOv3Schema(t *testing.T) {
	// Find the po-default-browser template
	var template *DocumentTemplateVersion
	for _, tmpl := range DefaultDocumentTemplateVersions() {
		if tmpl.TemplateKey == "po-default-browser" {
			found := tmpl
			template = &found
			break
		}
	}
	if template == nil {
		t.Fatal("po-default-browser template not found in DefaultDocumentTemplateVersions()")
	}

	if template.ProfileCode != "po" {
		t.Fatalf("template profile = %q, want po", template.ProfileCode)
	}
	if template.SchemaVersion != 3 {
		t.Fatalf("template schema version = %d, want 3", template.SchemaVersion)
	}
	if template.Editor != "ckeditor5" {
		t.Fatalf("template editor = %q, want ckeditor5", template.Editor)
	}
	if template.ContentFormat != "html" {
		t.Fatalf("template content format = %q, want html", template.ContentFormat)
	}
	if strings.TrimSpace(template.Body) == "" {
		t.Fatal("template body is empty")
	}

	// Load PO v3 schema from DefaultDocumentTypeDefinitions()
	var poSchema *DocumentTypeSchema
	for _, def := range DefaultDocumentTypeDefinitions() {
		if def.Key == "po" {
			schema := def.Schema
			poSchema = &schema
			break
		}
	}
	if poSchema == nil {
		t.Fatal("PO document type definition not found")
	}

	body := template.Body

	// Skip sections that are auto-generated by docgen (not in the editor template):
	// - section "identificacao" (num "1") — auto-generated header
	// - section "historico" (num "10") — auto-generated revision history
	skipSections := map[string]bool{
		"identificacao": true,
		"historico":     true,
	}

	for _, section := range poSchema.Sections {
		if skipSections[section.Key] {
			continue
		}

		if !strings.Contains(body, section.Title) {
			t.Errorf("template body missing section title %q (key=%s)", section.Title, section.Key)
		}

		for _, field := range section.Fields {
			if !strings.Contains(body, field.Label) {
				t.Errorf("template body missing field label %q (section=%s, key=%s)", field.Label, section.Key, field.Key)
			}

			// Check table column labels
			for _, col := range field.Columns {
				if !strings.Contains(body, col.Label) {
					t.Errorf("template body missing table column label %q (section=%s, field=%s)", col.Label, section.Key, field.Key)
				}
			}

			// Check repeat item field labels
			for _, itemField := range field.ItemFields {
				if !strings.Contains(body, itemField.Label) {
					t.Errorf("template body missing repeat item label %q (section=%s, field=%s)", itemField.Label, section.Key, field.Key)
				}
			}
		}
	}
}
