package domain

import (
	"os"
	"strings"
	"testing"
)

func TestPOBrowserTemplateCoversPOv3Schema(t *testing.T) {
	// Find the po-default-browser template
	var template *DocumentTemplateVersion
	for _, tmpl := range DefaultDocumentTemplateVersions() {
		if tmpl.TemplateKey == "po-default-browser" {
			found := tmpl
			template = &found
			break
		}
	}
	if template == nil {
		t.Fatal("po-default-browser template not found in DefaultDocumentTemplateVersions()")
	}

	if template.ProfileCode != "po" {
		t.Fatalf("template profile = %q, want po", template.ProfileCode)
	}
	if template.SchemaVersion != 3 {
		t.Fatalf("template schema version = %d, want 3", template.SchemaVersion)
	}
	if template.Editor != "ckeditor5" {
		t.Fatalf("template editor = %q, want ckeditor5", template.Editor)
	}
	if template.ContentFormat != "html" {
		t.Fatalf("template content format = %q, want html", template.ContentFormat)
	}
	if strings.TrimSpace(template.Body) == "" {
		t.Fatal("template body is empty")
	}

	// Load PO v3 schema from DefaultDocumentTypeDefinitions()
	var poSchema *DocumentTypeSchema
	for _, def := range DefaultDocumentTypeDefinitions() {
		if def.Key == "po" {
			schema := def.Schema
			poSchema = &schema
			break
		}
	}
	if poSchema == nil {
		t.Fatal("PO document type definition not found")
	}

	body := template.Body

	// "identificacao" and "historico" are auto-generated by docgen on export.
	// "etapas" uses free-form input in the browser template — not schema-driven.
	skipSections := map[string]bool{
		"identificacao": true,
		"historico":     true,
		"etapas":        true,
	}

	for _, section := range poSchema.Sections {
		if skipSections[section.Key] {
			continue
		}

		if !strings.Contains(body, section.Title) {
			t.Errorf("template body missing section title %q (key=%s)", section.Title, section.Key)
		}

		for _, field := range section.Fields {
			if !strings.Contains(body, field.Label) {
				t.Errorf("template body missing field label %q (section=%s, key=%s)", field.Label, section.Key, field.Key)
			}

			// Check table column labels
			for _, col := range field.Columns {
				if !strings.Contains(body, col.Label) {
					t.Errorf("template body missing table column label %q (section=%s, field=%s)", col.Label, section.Key, field.Key)
				}
			}

			// Check repeat item field labels
			for _, itemField := range field.ItemFields {
				if !strings.Contains(body, itemField.Label) {
					t.Errorf("template body missing repeat item label %q (section=%s, field=%s)", itemField.Label, section.Key, field.Key)
				}
			}
		}
	}
}

func TestDefaultDocumentTemplateVersionsPODefaultIsLast(t *testing.T) {
	var lastPO *DocumentTemplateVersion
	for _, tmpl := range DefaultDocumentTemplateVersions() {
		if tmpl.ProfileCode == "po" {
			found := tmpl
			lastPO = &found
		}
	}
	if lastPO == nil {
		t.Fatal("no PO template found in DefaultDocumentTemplateVersions()")
	}
	if lastPO.TemplateKey != "po-default-browser" {
		t.Fatalf("last PO template key = %q, want po-default-browser (in-memory repo uses last entry as default)", lastPO.TemplateKey)
	}
	if lastPO.Version != 1 {
		t.Fatalf("last PO template version = %d, want 1", lastPO.Version)
	}
}

func TestPOBrowserTemplateGoSQLParity(t *testing.T) {
	// Load Go seed template
	var goTemplate *DocumentTemplateVersion
	for _, tmpl := range DefaultDocumentTemplateVersions() {
		if tmpl.TemplateKey == "po-default-browser" {
			found := tmpl
			goTemplate = &found
			break
		}
	}
	if goTemplate == nil {
		t.Fatal("po-default-browser template not found in Go seed")
	}

	// Read SQL migration file
	migrationPath := "../../../../migrations/0057_seed_po_browser_template.sql"
	sqlBytes, err := os.ReadFile(migrationPath)
	if err != nil {
		t.Fatalf("read migration file: %v", err)
	}
	sqlContent := string(sqlBytes)

	// Verify template identity fields are present in migration SQL
	identityChecks := map[string]string{
		"template_key":   "'po-default-browser'",
		"profile_code":   "'po'",
		"schema_version": "3",
		"editor":         "'ckeditor5'",
		"content_format": "'html'",
		"name":           "'Procedimento Operacional'",
		"version":        "1",
	}
	for field, expected := range identityChecks {
		if !strings.Contains(sqlContent, expected) {
			t.Errorf("migration SQL missing %s = %s", field, expected)
		}
	}

	// Verify profile default update is present
	if !strings.Contains(sqlContent, "document_profile_template_defaults") {
		t.Error("migration SQL does not update document_profile_template_defaults")
	}
	if !strings.Contains(sqlContent, "template_key = 'po-default-browser'") {
		t.Error("migration SQL does not set profile default to po-default-browser")
	}
	if !strings.Contains(sqlContent, "template_version = 1") {
		t.Error("migration SQL does not set profile default version to 1")
	}

	// Extract body_html between $$ delimiters and compare with Go seed
	parts := strings.SplitN(sqlContent, "$$", 3)
	if len(parts) < 3 {
		t.Fatal("migration file does not contain $$ delimited body_html")
	}
	sqlBody := parts[1]

	goNormalized := strings.TrimSpace(strings.ReplaceAll(goTemplate.Body, "\r\n", "\n"))
	sqlNormalized := strings.TrimSpace(strings.ReplaceAll(sqlBody, "\r\n", "\n"))

	if goNormalized != sqlNormalized {
		t.Fatalf("Go seed body and SQL migration body differ.\nGo length=%d, SQL length=%d\nFirst difference at character %d",
			len(goNormalized), len(sqlNormalized), firstDiffIndex(goNormalized, sqlNormalized))
	}
}

func TestPOBrowserTemplate0058Parity(t *testing.T) {
	// Get canonical Go template body (same lookup as TestPOBrowserTemplateGoSQLParity)
	var goTemplate *DocumentTemplateVersion
	for _, tmpl := range DefaultDocumentTemplateVersions() {
		if tmpl.TemplateKey == "po-default-browser" {
			found := tmpl
			goTemplate = &found
			break
		}
	}
	if goTemplate == nil {
		t.Fatal("po-default-browser template not found in Go seed")
	}

	// Read 0058 migration file
	migrationPath := "../../../../migrations/0058_update_po_browser_template.sql"
	sqlBytes, err := os.ReadFile(migrationPath)
	if err != nil {
		t.Fatalf("read 0058 migration file: %v", err)
	}
	sqlContent := string(sqlBytes)

	// Extract body between $$ delimiters (same as 0057 parity test)
	parts := strings.SplitN(sqlContent, "$$", 3)
	if len(parts) < 3 {
		t.Fatal("0058 migration does not contain $$ delimited body_html")
	}
	sqlBody := parts[1]

	goNormalized := strings.TrimSpace(strings.ReplaceAll(goTemplate.Body, "\r\n", "\n"))
	sqlNormalized := strings.TrimSpace(strings.ReplaceAll(sqlBody, "\r\n", "\n"))

	if goNormalized != sqlNormalized {
		t.Fatalf("0058 body_html differs from Go canonical body.\nGo length=%d, SQL length=%d\nFirst difference at character %d",
			len(goNormalized), len(sqlNormalized), firstDiffIndex(goNormalized, sqlNormalized))
	}
}

func firstDiffIndex(a, b string) int {
	minLen := len(a)
	if len(b) < minLen {
		minLen = len(b)
	}
	for i := 0; i < minLen; i++ {
		if a[i] != b[i] {
			return i
		}
	}
	return minLen
}
