INSERT INTO metaldocs.document_families (code, name, description)
VALUES
  ('record', 'Record', 'Controlled record generated by an operational process')
ON CONFLICT (code) DO NOTHING;

INSERT INTO metaldocs.document_profiles (
  code, family_code, name, description, review_interval_days
)
VALUES
  ('po', 'procedure', 'PO', 'Procedimento operacional da Metal Nobre', 365),
  ('it', 'work_instruction', 'IT', 'Instrucao de trabalho da Metal Nobre', 180),
  ('rg', 'record', 'RG', 'Registro operacional da Metal Nobre', 365)
ON CONFLICT (code) DO NOTHING;

INSERT INTO metaldocs.document_profile_schema_versions (
  profile_code, version, metadata_rules_json, is_active
)
VALUES
  ('po', 1, '[]'::jsonb, TRUE),
  ('it', 1, '[]'::jsonb, TRUE),
  ('rg', 1, '[]'::jsonb, TRUE)
ON CONFLICT (profile_code, version) DO NOTHING;

INSERT INTO metaldocs.document_profile_governance (
  profile_code, workflow_profile, review_interval_days, approval_required, retention_days, validity_days
)
VALUES
  ('po', 'standard_approval', 365, TRUE, 3650, 0),
  ('it', 'standard_approval', 180, TRUE, 3650, 0),
  ('rg', 'standard_approval', 365, TRUE, 3650, 0)
ON CONFLICT (profile_code) DO NOTHING;

INSERT INTO metaldocs.document_departments (code, name, description)
VALUES
  ('sgq', 'SGQ', 'Sistema de Gestao da Qualidade'),
  ('operacoes', 'Operacoes', 'Operacao e execucao do processo'),
  ('manutencao', 'Manutencao', 'Manutencao de equipamentos e infraestrutura'),
  ('compras', 'Compras', 'Compras e suprimentos'),
  ('logistica', 'Logistica', 'Logistica e expedicao'),
  ('financeiro', 'Financeiro', 'Financeiro e controladoria'),
  ('comercial', 'Comercial', 'Relacionamento com clientes e vendas'),
  ('rh', 'RH', 'Recursos humanos'),
  ('ti', 'TI', 'Tecnologia da informacao')
ON CONFLICT (code) DO NOTHING;

INSERT INTO metaldocs.document_process_areas (code, name, description)
VALUES
  ('quality', 'Quality', 'Quality management and ISO-aligned operations'),
  ('marketplaces', 'Marketplaces', 'Marketplace commercial and operational routines'),
  ('commercial', 'Commercial', 'Commercial and customer-facing processes'),
  ('purchasing', 'Purchasing', 'Procurement and supplier acquisition processes'),
  ('logistics', 'Logistics', 'Logistics, shipping and fulfillment processes'),
  ('finance', 'Finance', 'Financial and fiscal control processes')
ON CONFLICT (code) DO NOTHING;
