-- 0057_seed_po_browser_template.sql
-- Insert production PO browser template (po-default-browser v1) and update PO profile default.
-- Covers all 8 editable sections of PO v3 schema (sections 2-9).
-- Sections 1 (Identificação) and 10 (Histórico de Revisões) are auto-generated by docgen on export.
-- IMPORTANT: body_html must match the Go seed in domain/template.go (validated by TestPOBrowserTemplateGoSQLParity).

INSERT INTO metaldocs.document_template_versions (
  template_key, version, profile_code, schema_version, name,
  editor, content_format, body_html, definition_json
)
VALUES (
  'po-default-browser',
  1,
  'po',
  3,
  'Procedimento Operacional',
  'ckeditor5',
  'html',
  $$<section class="md-doc-shell">
  <header class="md-doc-header">
    <h1>Procedimento Operacional</h1>
    <p class="md-doc-type">Tipo: PO</p>
  </header>

  <section class="md-section">
    <h2>2. Identificação do Processo</h2>
    <p><strong>Objetivo</strong></p>
    <p><span class="restricted-editing-exception">Descreva o objetivo deste procedimento, incluindo o resultado esperado ao final da execução.</span></p>
    <p><strong>Escopo</strong></p>
    <p><span class="restricted-editing-exception">Defina os limites de aplicação deste procedimento: onde começa, onde termina e o que está fora do escopo.</span></p>
    <p><strong>Cargo responsável</strong></p>
    <p><span class="restricted-editing-exception">Informe o cargo ou função responsável pela execução deste procedimento.</span></p>
    <p><strong>Canal / Contexto</strong></p>
    <p><span class="restricted-editing-exception">Descreva o canal ou contexto em que este procedimento se aplica.</span></p>
    <p><strong>Participantes</strong></p>
    <p><span class="restricted-editing-exception">Liste os cargos, funções ou áreas que participam da execução deste procedimento.</span></p>
  </section>

  <section class="md-section">
    <h2>3. Entradas e Saídas</h2>
    <p><strong>Entradas</strong></p>
    <p><span class="restricted-editing-exception">Liste os insumos, informações ou materiais necessários para iniciar o processo.</span></p>
    <p><strong>Saídas</strong></p>
    <p><span class="restricted-editing-exception">Liste os produtos, resultados ou entregas gerados ao final do processo.</span></p>
    <p><strong>Documentos relacionados</strong></p>
    <p><span class="restricted-editing-exception">Liste documentos, formulários ou registros utilizados ou gerados durante o processo.</span></p>
    <p><strong>Sistemas utilizados</strong></p>
    <p><span class="restricted-editing-exception">Liste os sistemas, ferramentas ou plataformas utilizadas na execução do processo.</span></p>
  </section>

  <section class="md-section">
    <h2>4. Visão Geral do Processo</h2>
    <p><strong>Descrição do processo</strong></p>
    <div class="restricted-editing-exception"><p>Descreva o processo de forma detalhada, incluindo o contexto, fluxo geral e principais decisões envolvidas.</p></div>
    <p><strong>Ferramenta do fluxograma</strong></p>
    <p><span class="restricted-editing-exception">Informe a ferramenta utilizada para criar o fluxograma (ex: Bizagi, Visio, Miro).</span></p>
    <p><strong>Link do fluxograma</strong></p>
    <p><span class="restricted-editing-exception">Cole o link de acesso ao fluxograma do processo.</span></p>
    <p><strong>Diagrama</strong></p>
    <div class="restricted-editing-exception"><p>Insira ou descreva o diagrama do processo. Pode utilizar imagens ou representações textuais.</p></div>
  </section>

  <section class="md-section">
    <h2>5. Detalhamento das Etapas</h2>
    <div class="restricted-editing-exception">
      <h3>Etapa 1</h3>
      <p><strong>Número:</strong> Informe o número desta etapa</p>
      <p><strong>Título:</strong> Descreva o título da etapa</p>
      <p><strong>Responsável:</strong> Cargo ou função responsável por esta etapa</p>
      <p><strong>Prazo / SLA:</strong> Prazo esperado para conclusão</p>
      <p><strong>Descrição:</strong></p>
      <p>Descreva o que deve ser feito nesta etapa, incluindo instruções específicas.</p>
      <p><strong>Observações:</strong> Informações complementares ou ressalvas</p>
      <p><strong>Alertas / Desvios:</strong> Condições que exigem atenção especial ou ações corretivas</p>
      <hr>
      <p><em>Duplique o bloco acima para adicionar mais etapas.</em></p>
    </div>
  </section>

  <section class="md-section">
    <h2>6. Controle e Exceções</h2>
    <p><strong>Pontos de controle</strong></p>
    <p><span class="restricted-editing-exception">Descreva os pontos de verificação, aprovação ou controle existentes no processo.</span></p>
    <p><strong>Exceções e desvios</strong></p>
    <p><span class="restricted-editing-exception">Descreva situações excepcionais e como devem ser tratadas.</span></p>
  </section>

  <section class="md-section">
    <h2>7. Indicadores de Desempenho</h2>
    <p><strong>KPIs</strong></p>
    <figure class="table restricted-editing-exception">
      <table>
        <thead>
          <tr><th>Indicador / KPI</th><th>Meta</th><th>Frequência</th></tr>
        </thead>
        <tbody>
          <tr><td>Ex: Taxa de retrabalho</td><td>Ex: &lt; 5%</td><td>Ex: Mensal</td></tr>
        </tbody>
      </table>
    </figure>
  </section>

  <section class="md-section">
    <h2>8. Documentos e Referências</h2>
    <figure class="table restricted-editing-exception">
      <table>
        <thead>
          <tr><th>Código</th><th>Título / Descrição</th><th>Link / Localização</th></tr>
        </thead>
        <tbody>
          <tr><td>Ex: PO-001</td><td>Ex: Procedimento de compras</td><td>Ex: /docs/po-001</td></tr>
        </tbody>
      </table>
    </figure>
  </section>

  <section class="md-section">
    <h2>9. Glossário</h2>
    <figure class="table restricted-editing-exception">
      <table>
        <thead>
          <tr><th>Termo</th><th>Definição</th></tr>
        </thead>
        <tbody>
          <tr><td>Ex: SLA</td><td>Ex: Acordo de nível de serviço</td></tr>
        </tbody>
      </table>
    </figure>
  </section>
</section>$$,
  '{}'::jsonb
)
ON CONFLICT (template_key, version) DO NOTHING;

-- Update PO profile default to the new browser template
UPDATE metaldocs.document_profile_template_defaults
SET template_key = 'po-default-browser',
    template_version = 1,
    assigned_at = NOW()
WHERE profile_code = 'po';

-- Insert if no default exists yet
INSERT INTO metaldocs.document_profile_template_defaults (profile_code, template_key, template_version)
VALUES ('po', 'po-default-browser', 1)
ON CONFLICT (profile_code) DO NOTHING;
