// Committed SHA-256 of the current Layout IR snapshot. Regenerated ONLY
// when a deliberate renderer version bump happens (see the drift gate
// test). Do NOT edit this file by hand to silence the drift test.

export const RECORDED_IR_HASH = "6850fc11ee7d69d92f6ace60f65cac5bad5795d2e4e7794315d612afd19b1971";
export const RECORDED_RENDERER_VERSION = "1.0.0";
