// Committed SHA-256 of the current Layout IR snapshot. Regenerated ONLY
// when a deliberate renderer version bump happens (see the drift gate
// test). Do NOT edit this file by hand to silence the drift test.

export const RECORDED_IR_HASH = "464ee0fc122141330e95892b1fd95b8992e00e33e66cee683d3ac6c5e6fc761a";
export const RECORDED_RENDERER_VERSION = "1.0.0";
