// Committed SHA-256 of the current Layout IR snapshot. Regenerated ONLY
// when a deliberate renderer version bump happens (see the drift gate
// test). Do NOT edit this file by hand to silence the drift test.

export const RECORDED_IR_HASH = "085e061d9eeaa99cda284e4ea1a925ef6a48bdb7df0b0834b281a6ca057abcad";
export const RECORDED_RENDERER_VERSION = "1.0.0";
