import {
  Essentials,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Link,
  AutoLink,
  List,
  Table,
  TableToolbar,
  TableProperties,
  TableCellProperties,
  TableColumnResize,
  TableCaption,
  Image,
  ImageToolbar,
  ImageStyle,
  ImageResize,
  ImageCaption,
  ImageUpload,
  ImageInsert,
  Alignment,
  FontFamily,
  FontSize,
  FontColor,
  FontBackgroundColor,
  RemoveFormat,
  StandardEditingMode,
  RestrictedEditingMode,
  Autosave,
  GeneralHtmlSupport,
  BlockQuote,
  HorizontalLine,
  PasteFromOffice,
} from 'ckeditor5';

// MetalDocs custom plugins are added in later tasks.
// Each primitive plugin appends itself to these lists via a registration helper
// (see editorConfig.ts extraPlugins). For now, we define the CK5-native baseline.

const SHARED_BASE = [
  Essentials,
  Paragraph,
  Heading,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Link,
  AutoLink,
  List,
  Table,
  TableToolbar,
  TableProperties,
  TableCellProperties,
  TableColumnResize,
  TableCaption,
  Image,
  ImageToolbar,
  ImageStyle,
  ImageResize,
  ImageCaption,
  ImageUpload,
  ImageInsert,
  Alignment,
  FontFamily,
  FontSize,
  FontColor,
  FontBackgroundColor,
  RemoveFormat,
  BlockQuote,
  HorizontalLine,
  PasteFromOffice,
  Autosave,
  GeneralHtmlSupport,
];

export const AUTHOR_PLUGINS = [
  ...SHARED_BASE,
  StandardEditingMode,
];

export const FILL_PLUGINS = [
  ...SHARED_BASE,
  RestrictedEditingMode,
];
