export const AUTHOR_TOOLBAR: readonly string[] = [
  'insertMddmSection',
  'insertMddmRepeatable',
  'insertMddmField',
  'insertMddmRichBlock',
  'insertTable',
  'imageUpload',
  '|',
  'heading',
  'bulletedList',
  'numberedList',
  'alignment',
  '|',
  'bold',
  'italic',
  'underline',
  'fontSize',
  'fontColor',
  'link',
  'removeFormat',
  '|',
  'restrictedEditingException',
  'restrictedEditingExceptionBlock',
  '|',
  'undo',
  'redo',
];

export const FILL_TOOLBAR: readonly string[] = [
  'undo',
  'redo',
  '|',
  'bold',
  'italic',
  'underline',
  'link',
  '|',
  'bulletedList',
  'numberedList',
  'alignment',
  'fontColor',
  '|',
  'goToPreviousRestrictedEditingException',
  'goToNextRestrictedEditingException',
];

