import * as CKEditor from "ckeditor5";

const {
  Alignment,
  AutoImage,
  Autoformat,
  Base64UploadAdapter,
  BlockQuote,
  Bold,
  DecoupledEditor,
  Essentials,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Italic,
  Link,
  List,
  Paragraph,
  Table,
  TableToolbar,
  Underline,
} = CKEditor as Record<string, any>;

export const editorClass = DecoupledEditor as any;

export const editorConfig = {
  licenseKey: "GPL",
  plugins: [
    Essentials,
    Paragraph,
    Heading,
    Bold,
    Italic,
    Underline,
    Link,
    List,
    Table,
    TableToolbar,
    Image,
    ImageUpload,
    ImageToolbar,
    ImageStyle,
    ImageResize,
    ImageCaption,
    ImageInsert,
    AutoImage,
    Base64UploadAdapter,
    Autoformat,
    Alignment,
    FontFamily,
    FontSize,
    FontColor,
    FontBackgroundColor,
    BlockQuote,
  ],
  toolbar: {
    items: [
      "undo",
      "redo",
      "|",
      "heading",
      "|",
      "fontFamily",
      "fontSize",
      "fontColor",
      "fontBackgroundColor",
      "|",
      "bold",
      "italic",
      "underline",
      "link",
      "|",
      "alignment",
      "bulletedList",
      "numberedList",
      "blockQuote",
      "insertTable",
      "uploadImage",
    ],
    shouldNotGroupWhenFull: true,
  },
};
